/*
 * compute
 *
 * Manage instances in cloud.
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package compute

type Instance struct {
	Image string `json:"image"`

	SwapSize string `json:"swapSize,omitempty"`

	Type string `json:"type"`

	Label string `json:"label"`
}

// AssertInstanceRequired checks if the required fields are not zero-ed
func AssertInstanceRequired(obj Instance) error {
	elements := map[string]interface{}{
		"image": obj.Image,
		"type":  obj.Type,
		"label": obj.Label,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseInstanceRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Instance (e.g. [][]Instance), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseInstanceRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aInstance, ok := obj.(Instance)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertInstanceRequired(aInstance)
	})
}
