/*
 * compute
 *
 * Manage instances in cloud.
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package compute

type CreateRequest struct {
	Foo string `json:"foo,omitempty"`
}

// AssertCreateRequestRequired checks if the required fields are not zero-ed
func AssertCreateRequestRequired(obj CreateRequest) error {
	return nil
}

// AssertRecurseCreateRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of CreateRequest (e.g. [][]CreateRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseCreateRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aCreateRequest, ok := obj.(CreateRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertCreateRequestRequired(aCreateRequest)
	})
}
