/*
 * compute
 *
 * Manage instances in cloud.
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package compute

type GetInstanceResponse struct {
	Instances []CreatedInstance `json:"instances,omitempty"`
}

// AssertGetInstanceResponseRequired checks if the required fields are not zero-ed
func AssertGetInstanceResponseRequired(obj GetInstanceResponse) error {
	for _, el := range obj.Instances {
		if err := AssertCreatedInstanceRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseGetInstanceResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of GetInstanceResponse (e.g. [][]GetInstanceResponse), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseGetInstanceResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aGetInstanceResponse, ok := obj.(GetInstanceResponse)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertGetInstanceResponseRequired(aGetInstanceResponse)
	})
}
