/*
 * Growd Document Generator
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.11
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package compute

import (
	"log"
	"net/http"
	"os"
	"strings"
)

// OpenApiController binds http requests to an api service and writes the service results to the http response
type OpenApiController struct {
	errorHandler ErrorHandler
}

// OpenApiOption for how the controller is set up.
type OpenApiOption func(*OpenApiController)

// WithOpenApiErrorHandler inject ErrorHandler into controller
func WithOpenApiErrorHandler(h ErrorHandler) OpenApiOption {
	return func(c *OpenApiController) {
		c.errorHandler = h
	}
}

// NewOpenApiController creates a default api controller
func NewOpenApiController(opts ...OpenApiOption) Router {
	controller := &OpenApiController{

		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the OpenApiController
func (c *OpenApiController) Routes() Routes {
	return Routes{
		{
			"OpenApiSpec",
			strings.ToUpper("Get"),
			"/openapi",
			c.OpenApiSpec,
		},
	}
}

// OpenApiSpec -
func (c *OpenApiController) OpenApiSpec(w http.ResponseWriter, r *http.Request) {
	f, err := os.Open("api/openapi.yaml")
	if err != nil {
		log.Fatalln(err.Error())
	}
	fi, err := f.Stat()
	if err != nil {
		log.Fatalln(err.Error())
	}
	buf := make([]byte, fi.Size())
	f.Read(buf)

	w.Header().Set("Content-Type", "application/yaml; charset=UTF-8")
	w.Write(buf)
	// If an error occurred, encode the error with the status code
	if err != nil {
		w.WriteHeader(400)
		return
	}
	// If no error, encode the body and the result code

}
